import type { Metadata } from "next";
import "./globals.css";
import { GlobalToastRegion } from "@/app/_components/Aria/Toast/GlobalToastRegion";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        {children}
        <GlobalToastRegion />
      </body>
    </html>
  );
}
